version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: olimpiadas_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-secret}
      MYSQL_DATABASE: ${DB_DATABASE:-olimpiadas}
      MYSQL_USER: ${DB_USERNAME:-olimpiadas_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${DB_PORT:-3306}:3306"
    networks:
      - olimpiadas_network
    healthcheck:
      test: ["CMD", "mysql", "-u${DB_USERNAME:-olimpiadas_user}", "-p${DB_PASSWORD:-secret}", "-e", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Laravel Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: olimpiadas_app
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      # Application
      APP_NAME: ${APP_NAME:-Olimpiadas Management System}
      APP_ENV: ${APP_ENV:-production}
      APP_KEY: ${APP_KEY}
      APP_DEBUG: ${APP_DEBUG:-false}
      APP_URL: ${APP_URL:-http://localhost}
      
      # Database
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE:-olimpiadas}
      DB_USERNAME: ${DB_USERNAME:-olimpiadas_user}
      DB_PASSWORD: ${DB_PASSWORD:-secret}
      
      # Cache & Session
      CACHE_DRIVER: ${CACHE_DRIVER:-file}
      SESSION_DRIVER: ${SESSION_DRIVER:-file}
      QUEUE_CONNECTION: ${QUEUE_CONNECTION:-sync}
      
      # Logging
      LOG_CHANNEL: ${LOG_CHANNEL:-stack}
      LOG_LEVEL: ${LOG_LEVEL:-info}
    volumes:
      - storage_data:/var/www/html/storage
      - ./docker/env/.env:/var/www/html/.env
    ports:
      - "${APP_PORT:-80}:80"
    networks:
      - olimpiadas_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/up"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  olimpiadas_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  storage_data:
    driver: local

